mongodb/amboy

queue/unordered.go

JIRA: https://jira.mongodb.org/browse/MAKE-661
`Results()` and the `Complete()` goroutine would race to read/write numCompleted.

MAKE-661: fix unordered queue race to access numCompleted

---

queue/remote_base.go
queue/remote_unordered.go

the underlying mongodb driver and dispatcher checks for dispatchability so we don't need to check for it in the queues

MAKE-1123: avoid blocking jobs

---

pool/local.go
queue/dispatcher.go
queue/driver_mongo.go
queue/remote_base.go
queue/remote_ordered.go
queue/scope.go

JIRA: https://jira.mongodb.org/browse/MAKE-1215
I'm not entirely confident that this is why barque's scope jobs don't restart when the app server restarts but my current theory is that when the job gets stuck in progress, `(*mongoDriver).getNextQuery()` finds jobs that have exceeded the lock timeout but they get filtered by `isDispatchable()` in `(*dispatcherImpl).Dispatch()`. This just allows jobs that have exceeded the lock timeout. to be re-dispatched.

MAKE-1215: re-dispatch job on lock timeout

---

interface.go
job/base.go
job/base_test.go
registry/interchange.go
registry/interchange_test.go
registry/mock_job_for_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13538
Implement retryable options with a flag indicating if the job can retry and how many times it's retried. They're no-ops until [EVG-13540](https://jira.mongodb.org/browse/EVG-13540) is implemented to have a retry handler, but they are serialized so they can be stored in MongoDB.

EVG-13538: add option for retryable job

---

evergreen.yaml
queue/driver_mongo.go
queue/fixed.go
queue/mock_job_test.go
queue/priority.go
queue/queue_test.go
queue/remote_test.go
queue/scope.go
queue/scope_test.go
queue/shuffled.go
queue/shuffled_test.go
queue/sqs.go
queue/sqs_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13718
* Make the local scope manager operations atomic. Previously, it was possible to partially acquire/release the scopes that you pass in.
* Implement applying scopes for implementations that already use a local scope manager.
* Make the queue implementations consistent with the remote queue/Mongo driver, which acquires the scope in `Save()`.
* Write common queue interface tests for all implementations that have scopes.
* Fix some test coverage issues where a bunch of implementations that support WaitUntil/DispatchBy wouldn't test them.

EVG-13718: implement applying scope on enqueue for local scope manager implementations

---

pool/helpers.go
queue/queue_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13760
MaxTime currently does nothing if you set it except set an error message after the job completes. It should now behave as expected and cancel the job's `Run()` context after MaxTime (which must be configured before the job has been enqueued).

EVG-13760: cancel the job's context after MaxTime elapses

---

glide.lock
interface.go
job/base.go
job/base_test.go
makefile
registry/interchange.go
registry/interchange_test.go
registry/mock_job_for_test.go
vendor/github.com/evergreen-ci/utility/checksum.go
vendor/github.com/evergreen-ci/utility/checksum_test.go
vendor/github.com/evergreen-ci/utility/file_test.go
vendor/github.com/evergreen-ci/utility/http_test.go
vendor/github.com/evergreen-ci/utility/io.go
vendor/github.com/evergreen-ci/utility/io_test.go
vendor/github.com/evergreen-ci/utility/network_test.go
vendor/github.com/evergreen-ci/utility/optional.go
vendor/github.com/evergreen-ci/utility/random.go
vendor/github.com/evergreen-ci/utility/random_test.go
vendor/github.com/evergreen-ci/utility/slice.go
vendor/github.com/evergreen-ci/utility/slice_test.go
vendor/github.com/evergreen-ci/utility/time.go
vendor/github.com/evergreen-ci/utility/time_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13545
* Add `NeedsRetry` option indicating whether the job should retry after it's been marked complete.
* Separate retry input options from retry output info to deal with optional input configuration. Instead of having a separate `SetRetryable` method, you can just call `UpdateRetryInfo` with `Retryable = true`.

EVG-13545: add option for job that needs to retry

---

interface.go
job/base.go
job/base_test.go
registry/mock_job_for_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13539
* Add new `AddRetryableError` method to add an error and mark the job as needing to retry.
* Fix some incorrect/outdated documentation.

EVG-13539: create job method to add error and mark for retry

---

pool/helpers.go
pool/local.go
pool/local_test.go
pool/single.go

JIRA: https://jira.mongodb.org/browse/EVG-13835
The local workers were not adding goroutines to the WaitGroup in a thread-safe way because they were adding themselves within a goroutine rather than the main thread. If `Close()` is called, once the WaitGroup count reaches 0, no goroutine is allowed to increment the count again until `(sync.WaitGroup).Wait()` finishes. Therefore, if a new goroutine starts (e.g. a goroutine panics and restarts itself), it will add itself to the WaitGroup and can cause a panic. I fixed this by locking `(sync.WaitGroup).Add()` which prevents concurrent access to the Runner's WaitGroup between the main thread and the goroutine workers.

EVG-13835: safely add goroutines to WaitGroup in local runner

---

meta.go
pool/helpers.go
queue/dispatcher.go
queue/driver_mongo.go
queue/fixed.go
queue/group_remote_mongo_single.go
queue/ordered.go
queue/priority.go
queue/queue_test.go
queue/remote_base.go
queue/remote_ordered.go
queue/util.go

JIRA: https://jira.mongodb.org/browse/EVG-13652
A job got dispatched and the lock ping thread started, but the job never ran. The only places I could see where a job could be dispatched without running were a few exceptional error cases in between the dispatcher starting the lock ping thread and the `job.Run()` call. I made it so that all the exit conditions in between those two events cause the dispatcher to release the job. Since I didn't see any of the exceptional error logs in Splunk, I'm not confident that one of these errors was the cause, but the logging should be better now so we can diagnose it better if it recurs.
* Release any job that successfully gets dispatched but errors before it can run the job.  
* Refactor the dispatch attempt loop to be more readable.
* Add more …

EVG-13652: release dispatched jobs that error before they execute

---

evergreen.yaml

JIRA: https://jira.mongodb.org/browse/EVG-14017

EVG-14017: use MongoDB 4.0 in CI tests

---

interface.go
pool/mock_queue_test.go
queue/adaptive_order.go
queue/fixed.go
queue/group_remote_mongo.go
queue/group_remote_mongo_single.go
queue/group_util.go
queue/ordered.go
queue/priority.go
queue/remote.go
queue/remote_base.go
queue/remote_ordered.go
queue/remote_ordered_test.go
queue/remote_test.go
queue/remote_unordered.go
queue/retry.go
queue/shuffled.go
queue/sqs.go

JIRA: https://jira.mongodb.org/browse/EVG-13540
Patch: https://evergreen.mongodb.com/version/6025b8cc0ae60674b23eac62
* Add a Close method for queues to clean up (i.e. close their worker pools, stop the retry handler).
* Add retry handler options for MongoDB queues.
* Fix one deadlock in the retry handler between the workers and Close.

EVG-13540: reorganize to propagate retry handler options

---

queue/group_remote_mongo.go
queue/group_test.go
queue/group_util.go

JIRA: https://jira.mongodb.org/browse/EVG-14016
Addressing two different issues in the two MongoDB queue group implementations:
* For the single group queue (i.e. the one we use nowadays), for N items in the cache queue, the cache iterator was always returning N copies of the last item in the cache's queue rather than the N items individually.
* For the older queue (likely the legacy implementation and is unused now), every time the group queues were periodically pruned, if a queue wasn't accessed within its TTL, it would be deleted even if the queue wasn't finished processing all its jobs. In comparison, the single group implementation only prunes queues that have completed all their jobs. I'm not sure why it was implemented this way, but it means that every time we pruned the legacy …

EVG-14016: avoid capturing modified value in cache iterator loop and do not prune queues whose TTLs has expired

---

queue/driver_mongo.go

JIRA: https://jira.mongodb.org/browse/EVG-14085
For jobs in group queues, the document `_id` is the `(registry.JobInterchange).Name`, which includes the group name. The `(amboy.Job).ID()` excludes the group.

EVG-14085: handle deletion of jobs in group queues whose DispatchBy has been exceeded

---

interface.go
job/base.go
job/base_test.go
queue/driver.go
queue/driver_mongo.go
queue/driver_test.go
queue/mock_test.go
queue/remote_base.go
queue/retry.go
queue/util.go
registry/interchange_test.go
registry/mock_job_for_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13540
Patch: https://evergreen.mongodb.com/version/602c406ec9ec445b6f7bcd8c
Jobs in queue groups are basically the same as regular ungrouped jobs, but they have the group name prepended to them (i.e. the `_id` format is `${groupName}.${jobID}`). The driver deals with adding the group name when it goes into the DB and when queries are made on a queue group, the driver handles re-adding the group name to the query, so that the Amboy end user never has to deal with a grouped job queue differently from a regular job queue.
Since each retry job needs to have a unique `_id`, I originally just glommed the attempt number at the end of the job ID in the retry handler. However, this makes it hard to get jobs out of the driver (e.g. for the Nth job attempt, …

EVG-13540: handle retryable jobs IDs in the driver

---

interface.go
queue/driver_mongo.go
queue/mock_test.go
queue/queue_test.go
queue/remote_base.go
queue/retry.go
queue/retry_test.go
stats.go

JIRA: https://jira.mongodb.org/browse/EVG-13540
* Add unit testing and integration testing for the retry handler.
* Make some minor fixes to the retry handler around locking, restoring in-memory job state, and loading the job from the DB.

EVG-13540: add unit and integration tests for retry handler

---

interface.go
job/base.go
job/base_test.go
queue/driver.go
queue/driver_mongo.go
queue/driver_test.go
queue/mock_test.go
queue/queue_test.go
queue/remote_base.go
queue/retry.go
queue/retry_test.go
registry/mock_job_for_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13540
Patch: https://evergreen.mongodb.com/version/602fe3331e2d171e697ea37a
* Add configurable wait interval between checking for new jobs.
* Safely unset the scopes the old job was holding onto in the retry handler and change the method to `CompleteAndPut()`. This is to handle the case in which the old job is trying to atomically hand the scopes to the new job. The job has to hold them until the retry handler finishes processing the job, after which point it should release the scopes.
* Try multiple times to mark the job as processed using `CompleteRetry()`. [EVG-13784](https://jira.mongodb.org/browse/EVG-13784) will deal with the edge case of  it failing to save the job by ensuring the job does eventually unset NeedsRetry and its scopes (e.g. …

EVG-13540: make retry handler more robust

---

interface.go
job/base.go
job/base_test.go
queue/retry.go
queue/retry_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13544
Patch: https://evergreen.mongodb.com/version/60341d202a60ed7e784ec73f
Add job option to put an upper limit on the number of times it will retry.

EVG-13544: add option for max job attempts

---

errors.go
errors_test.go
queue/driver_mongo.go
queue/driver_test.go
queue/retry.go
queue/scope.go

JIRA: https://jira.mongodb.org/browse/EVG-13591
Patch: https://evergreen.mongodb.com/version/603437170305b916143db426
* Add a new error type, which is a type of duplicate key error, specifically for handling duplicate key errors due to another job holding the scope. For `amboy.EnqueueUniqueJob()`, it'll still squash errors due to acquiring duplicate scopes. If you want to check specifically for the duplicate scope case, you can just due `(amboy.Queue).Put()` and check for the duplicate key or scope error. The check is kind of fragile since it depends on parsing the error message text, but it seems like the server doesn't provide a nicer way to determine the index that caused the write failure.
* Return duplicate job scope errors if insertion fails because of the uniqueness constraint of …

EVG-13591: add error type for duplicate scopes

---

interface.go
job/base.go
queue/driver.go
queue/driver_mongo.go
queue/driver_test.go
queue/queue_test.go
queue/remote_base.go
queue/retry.go
queue/retry_test.go
queue/util.go

JIRA: https://jira.mongodb.org/browse/EVG-13784
* Add a goroutine to monitor for job that are in the process of retrying but are not actively marked as retrying (i.e. the lock timeout is exceeded).
* Add a driver method to return retryable jobs based on a filter.
* Atomically lock a retry job to a single in-memory queue's retry handler.
* Move a few random helper functions to more appropriate places.

EVG-13784: monitor stale retrying jobs

---

interface.go
job/base.go
queue/adaptive_order_storage_test.go
queue/mock_test.go
queue/remote_base.go
queue/retry.go
queue/retry_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13541
https://jira.mongodb.org/browse/EVG-13542
Patch: https://evergreen.mongodb.com/version/60366e44a4cf47157e163468
* Add settings to modify DispatchBy and WaitFor on retried jobs.
* Rename functions (i.e. CompleteRetry -> CompleteRetrying and CompleteAndPut -> CompleteRetryingAndPut) to make it more explicit that this is marking a retrying job as processed (instead of marking a regular job as completed executing).
* Push job metadata updates into the queue level to be consistent with guarantees on other queue methods (e.g. Put must set the job creation time).

EVG-13541, EVG-13542: add options for DispatchBy and WaitFor

---

benchmarks/harness.go
glide.lock
makefile
management/management_test.go
management/mongodb_test.go
queue/dispatcher_test.go
queue/driver_mongo.go
queue/driver_test.go
queue/queue_test.go
queue/remote_base.go
queue/remote_ordered_test.go
queue/remote_unordered_test.go
queue/retry.go
queue/retry_test.go
queue/util_for_test.go
vendor/github.com/evergreen-ci/utility/LICENSE
vendor/github.com/evergreen-ci/utility/optional.go
vendor/github.com/evergreen-ci/utility/time.go

JIRA: https://jira.mongodb.org/browse/EVG-13784
Patch: https://evergreen.mongodb.com/version/6037d7ae3e8e8669cc1ed35f
* Add integration tests for retry handler and remote queue.
* Add temporary internal interface for checking runtime stats of retry handler. I might get rid of it after [EVG-14111](https://jira.mongodb.org/browse/EVG-14111), since I mostly wanted it for more convenient testing.
* Reduce the amount of duplicate smok tests run.

EVG-13784: add retry handler and remote queue integration tests

---

interface.go
job/base.go
makefile
queue/remote_base.go
queue/retry.go
queue/retry_test.go
registry/mock_job_for_test.go

JIRA: https://jira.mongodb.org/browse/EVG-14111
Patch: https://evergreen.mongodb.com/version/603954f5e3c33156027ee2c1
* Add timing metadata for retrying.
* Remove temporary statsRetryHandler interface

EVG-14111: add retry metadata for start/end times

---

interface.go
queue/group_remote_mongo.go
queue/mock_test.go
queue/remote.go
queue/remote_base.go
queue/retry.go
queue/retry_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13922
* Add an option to set how frequently the monitor checks for stale retrying jobs.
* Add debug logging to help diagnose issues during rollout. They might be removed later once it's stable.

EVG-13922: make stale retrying monitor configurable and add debug logging for retry handler

---

queue/driver_mongo.go
queue/driver_test.go

JIRA: https://jira.mongodb.org/browse/EVG-14184
Pending should refer to jobs that are neither in progress nor completed. When I copied the query from the original stats code into the aggregation, the old code incorrectly counted in progress jobs as "pending" (which I assumed was correct, but it seems like it's just a bug). This fixes the stats to correctly count pending jobs as it's actually defined.

EVG-14184: do not count in progress jobs as pending in queue stats

---

interface.go
pool/helpers.go
queue/driver.go
queue/driver_mongo.go
queue/driver_test.go
queue/mock_test.go
queue/queue_test.go
queue/remote_base.go
queue/retry.go
queue/retry_test.go
registry/interchange.go
registry/interchange_test.go
registry/mock_job_for_test.go
rest/service_queue_job.go
retry.go
wait.go

JIRA: https://jira.mongodb.org/browse/EVG-14169
Patch: https://evergreen.mongodb.com/version/603d5a0f3066154680414970
I was originally hoping to be able to separate the retryable job from the non-retryable job more cleanly. However, it's not really possible to enforce that statically with an interface. It also had a problem where, even if you had a RetryableJob, retryability hinged mostly on the queue's built-in support for it. Instead of relying on a compile-time mechanism to deal with retryable jobs, I'm instead just going to use the `(JobRetryInfo).Retryable` feature flag as the marker for a retryable job.

EVG-14169: merge RetryableJob into Job interface

---

queue/group_remote_mongo.go
queue/queue_test.go
queue/remote.go
queue/retry.go
queue/retry_test.go

JIRA: https://jira.mongodb.org/browse/EVG-14169
Since the local scope manager is exported, I figured it would be preferable to export the useful implementations of other optional queue components like the retry handler.
Note: I intentionally returned the actual type rather than an interface.

EVG-14169: export the basic RetryHandler implementation

---

pool/helpers.go
queue/driver_mongo.go

JIRA: https://jira.mongodb.org/browse/EVG-14082
I increased the logging level to `info` in `executeJob` when there is no error and an error log's level to `warning` in the mongo go driver.

EVG-14082: Increase logging level for important information

---

interface.go
management/interface.go
management/management_test.go
management/queue.go
meta.go
pool/mock_queue_test.go
queue/adaptive_order.go
queue/driver.go
queue/driver_mongo.go
queue/driver_test.go
queue/limited.go
queue/limited_serializable.go
queue/mock_test.go
queue/ordered.go
queue/priority.go
queue/queue_test.go
queue/remote_base.go
queue/remote_unordered_test.go
queue/shuffled.go
queue/sqs.go

JIRA: https://jira.mongodb.org/browse/EVG-14244
* Rename `JobStats` to `JobInfo`.
* Instead of just returning the job status info, return more of the available information from the job.
* Move `JobStatusInfo.ID` to `JobInfo`, because it doesn't really belong on `JobStatusInfo`.
* Fix context handling in queue implementations for `JobStats` (`JobInfo`).
* Fix a few small correctness bugs in the queue-based remote management implementation.
* Add more docs and fix some existing ones.

EVG-14244: change job status method to return more job information

---

queue/group_remote_mongo.go

JIRA: https://jira.mongodb.org/browse/EVG-14067
Change the (mock) implementation of the MongoDB queue group to take retrying jobs into account before pruning the queue.

EVG-14067: do not prune queue group that still has retrying jobs

---

errors.go
errors_test.go
interface.go
periodic_test.go
queue/adaptive_order.go
queue/driver.go
queue/driver_mongo.go
queue/driver_test.go
queue/group_test.go
queue/limited.go
queue/limited_serializable.go
queue/mock_test.go
queue/ordered.go
queue/queue_test.go
queue/remote_base.go
queue/remote_ordered_test.go
queue/retry.go
queue/retry_test.go
queue/shuffled.go
queue/sqs.go
queue/util_for_test.go

JIRA: https://jira.mongodb.org/browse/EVG-14245
* Add `GetAllAttempts` to get all attempted executions tied to a single job ID.
* Make retryable queue methods return errors instead of booleans.
* Add error type for job not found in queue and use it for `Save`, `GetAttempt`, and `GetAllAttempts`.
* I decided to move the retrying logic for `CompleteRetrying` out of the remote queue implementation because it seems like that should be handled at a higher level. I only had that because I copied it from `Complete` (which retries because it does not return errors).
* Add tests for RetryableQueue-specific interface.

EVG-14245: add method to get all job attempts

---

cli/queue_management.go
management/filter_test.go
management/interface.go
management/management_test.go
management/mongodb.go
management/output.go
management/queue.go
queue/driver_mongo.go
queue/remote_base.go
rest/client_management.go
rest/service_management.go

JIRA: https://jira.mongodb.org/browse/EVG-14076
Note: I'm going to probably rework most of the remote management interface for [EVG-14270][EVG-14270], especially how the REST interface and how queue groups are handled, so that it supports more CRUD operations (for ops work) and does less aggregate statistics tracking (not as useful to us). This PR is mostly for the sake of completeness. Nothing is using the remote management interface right now, so it doesn't matter if it's perfect.
* Methods that complete also mark a job as not retrying. This is going to be refactored in [EVG-14270][EVG-14270] to make it easier to deal with retryable jobs and non-retryable jobs.
* Fix a bug where `JobIDsByState` didn't work if `ByGroups` was specified (note: `ByGroups` will likely be removed as part of …

EVG-14076: support retryable jobs in remote management

---

interface.go
makefile
management/management_test.go
queue/driver_test.go
queue/group_remote_mongo.go
queue/limited_serializable.go
queue/mock_test.go
queue/queue_test.go
queue/remote.go
queue/remote_base.go
queue/remote_ordered.go
queue/remote_ordered_test.go
queue/remote_unordered.go
queue/retry.go
queue/retry_test.go

JIRA: https://jira.mongodb.org/browse/EVG-14027
* Add feature flag to dynamically disable retryability at runtime.
* Group retryable queue options into common options struct.
* Provide a way to initialize retryable queues with the retry handler in their constructors rather than setting it after construction.
* Tidy up the makefile a bit.

EVG-14027: add feature flag for retryability

---

interface.go
management/queue.go
pool/abortable.go
pool/abortable_test.go
pool/helpers.go
pool/mock_queue_test.go
pool/rate_limiting.go
pool/rate_limiting_average.go
queue/adaptive_order.go
queue/driver_test.go
queue/limited.go
queue/limited_serializable.go
queue/mock_test.go
queue/ordered.go
queue/priority.go
queue/queue_test.go
queue/remote_base.go
queue/remote_unordered_test.go
queue/shuffled.go
queue/shuffled_test.go
queue/sqs.go
queue/sqs_test.go
rest/service_abortable_pool.go
rest/service_group_management.go
rest/service_queue_test.go

JIRA: https://jira.mongodb.org/browse/EVG-14302
* Return errors from `(Queue).Complete`.
* Fix some small bugs in queue implementations around logging and ignoring errors during `(Queue).Complete`.

EVG-14302: return errors from queue complete method

---

pool/helpers.go
queue/remote_base.go

JIRA: https://jira.mongodb.org/browse/EVG-14293
* Set the end time if the queue doesn't do it in `(Queue).Complete`.
* Don't unnecessarily update the job start time when the remote queue completes a job.

EVG-14293: do not report negative job runtime if context is done

---

job/base.go
queue/dispatcher.go
queue/dispatcher_test.go
queue/driver_test.go
queue/remote_unordered_test.go
queue/retry.go

JIRA: https://jira.mongodb.org/browse/EVG-14320
* Fix a bug where lock/save would set the retrying job to in progress.
* Fix an off-by-one in comparing job's max attempts against its current attempt.
* Fix some small errors in time duration logging.

EVG-14320: fix small bugs from end to end test

---

queue/driver_mongo.go
queue/util.go

JIRA: https://jira.mongodb.org/browse/EVG-14163
Scopes currently apply to the entire collection, including for queue groups (which are all in one collection). This doesn't play well with the fact that individual queues within the queue groups are supposed to be isolated from each other. The scopes index is now unique per-queue instead of per-collection.
The existing scopes indexes on the queue groups will have to be dropped and remade, but this is not really a problem since queue groups are not using scopes currently.

EVG-14163: isolate scopes for each queue in a queue group

---

pool/abortable.go
pool/helpers.go
pool/rate_limiting.go
queue/dispatcher_test.go
queue/ordered.go

Jira: https://jira.mongodb.org/browse/EVG-14519
Reduce log level to warning. I noticed that in evergreen staging, it would log for long-running jobs that failed to complete within the grace period for the app server shutdown, which was noisy when the apps were deployed/restarted. Since jobs  should re-run when they fail to get marked complete, it should be fine to reduce the log level.

EVG-14519: reduce logging level for Complete errors

---

job/base.go
queue/dispatcher.go
queue/driver_mongo.go

Jira: https://jira.mongodb.org/browse/EVG-14609
I've seen cases in staging and prod where jobs can be both in progress and completed at the same time, often for long-running jobs that have their context cancelled during the deploy. This bug seems to have been around for a long while, since I've seen this in jobs going back to at least January, so maybe it's always been a bug but has only been an issue now because more jobs use scopes. I believe this is because `(Job).MarkComplete` marks a job as complete but doesn't clear in progress and `(remoteQueue).Complete` will exit early and will _not_ do anything if the context is cancelled (i.e. when a deploy is shutting down the app server and the queue runner is closed).
Since it's invalid for a job to be both in progress and completed at the …

EVG-14609: prevent jobs from being both in progress and completed

---

queue/dispatcher.go
queue/dispatcher_test.go
queue/driver.go
queue/driver_mongo.go
queue/group_remote_mongo.go
queue/group_remote_mongo_single.go
queue/queue_test.go
queue/remote.go
queue/remote_base.go
queue/retry_test.go

Jira: https://jira.mongodb.org/browse/EVG-14617
* Close the dispatcher when the queue closes. This avoids two potential issues where a job can be stuck in progress:
1. The queue might close (when queue groups are pruned or the app restarts), causing all job running threads to finish their jobs and exit, but a job might still dispatch because the dispatcher is still running. This can leave a job stranded in progress because it's been dispatched but there's no job runner to handle it.
2. The dispatcher might also leave a job stuck in progress forever (until the app restarts) after a runner has already started executing a job. When the queue context is cancelled (e.g. during app shutdown), `Complete` might return early, which prevents the dispatcher from releasing the job.
* Close the driver …

EVG-14617: clean up queue resources during close

---

pool/helpers.go

Jira: https://jira.mongodb.org/browse/EVG-14561
Rather than log just the short error string when a job completes, log the extended error details, including the stack trace.

EVG-14561: log extended job error message when it completes

---

evergreen.yaml
interface.go
queue/driver.go
queue/driver_mongo.go
queue/driver_test.go

Jira: https://jira.mongodb.org/browse/EVG-14644
Currently, `Next` returns an unsorted cursor, so implicitly, it's returning job documents by the order of the index keys. This can lead to contention for the head of the queue, which becomes more contentious the more hosts (i.e. app servers) there are trying to get the next job. I added an option for MongoDB-backed queues to limit the number of jobs considered in each find query, and randomly shuffle the order of the jobs. I'm hoping this will reduce the issue of jobs dispatching too slowly when there are many pending jobs, but I can't be totally certain of the performance impact of this change.

EVG-14644: add option to consider a sample of jobs in Next

---

job/base.go
job/base_test.go
queue/driver_mongo.go

Jira: https://jira.mongodb.org/browse/EVG-14643
For whatever reason, the error count used to only be updated when it was going to be stored in the database, so if you just called `AddError`, it wouldn't change the in-memory error count. Now it does.

EVG-14643: update the error count when adding errors

---

interface.go
queue/driver_mongo.go
queue/queue_test.go

Jira: https://jira.mongodb.org/browse/EVG-14689
Exclude time restrictions (dispatch by, wait until, max time) from the job document if they're zero. The next job query is already indexed because there are indexes for the completed/in progress status; therefore, this change should not require any new indexes or anything and should be as performant as the old, non-omitted queries.

EVG-14689: omit optional time fields

---

makefile

Jira: https://jira.mongodb.org/browse/EVG-15573
* Make sure that the cache environment variables are defined if they're unset. If the environment already explicitly defines them, then use those. Otherwise, fall back to caching within the build directory.
* Standardize the check for test success/failure. `^PASS` is sufficient to ensure that there were tests and all the tests passed. If there's any test failure, data race, or the package has no tests, then the `^PASS` pattern won't appear in the test file output.

EVG-15573: ensure cache environment variables are set and simplify test success check

---

evergreen.yaml

`git.get_project` behaves incorrectly when using an absolute path in Windows (e.g. `${workdir}/amboy`) because it's not a native Windows absolute path (i.e. it doesn't look like `C:\data\mci\...` but is instead `/data/mci/...`). Although it would be preferable to have the CI system not behave inconsistently between Windows and non-Windows, it's easier to just change the invocations in the evergreen.yaml use to relative paths to avoid any Windows vs. Unix path issues.

EVG-15628: use relative path in evergreen.yaml

---

README.rst
evergreen.yaml
makefile

Jira: https://jira.mongodb.org/browse/EVG-15682
Remove the `DISABLE_COVERAGE` flag. The only thing that this does is when you run `make test-<package>`, it adds a summary line at the end of the go test output to include the percentage of lines covered that looks like this:
```
coverage:  <N>% of statements
```
I don't think this is particularly useful - instead, it's more useful is to run `make coverage-<package>` or `make html-coverage-<package>`, which produces more detailed information about code coverage rather than a single aggregate coverage number. Those coverage targets do not depend on `DISABLE_COVERAGE`.

EVG-15682: remove DISABLE_COVERAGE flag

---

queue/adaptive_order_storage_test.go

Jira: https://jira.mongodb.org/browse/EVG-15760
This fixes a test which was occasionally flaky because it had too few items, making it possible that it shuffles the items into the same order as the original. I increased the number of items in the slice to make it non-flaky.

EVG-15760: fix flaky adaptive order test

---

queue/group_test.go

Jira: https://jira.mongodb.org/browse/EVG-15683
The queue group pruning test is flaky on slow machines (MacOS and Windows) because the queues in the queue group do not finish running all the jobs before they get TTL'd and deleted from the queue group. I bumped the TTL for the slow machines.

EVG-15683: fix flaky queue group prune test

---

pool/helpers.go

Jira: https://jira.mongodb.org/browse/EVG-15956
Using the word "pending" in this case is deceptive because pending in an Amboy job refers to the state when the job is waiting in the queue to be dispatched to a worker. Here, it's being used to refer to the job's turnaround time (i.e. timespan between job submission and completion of its work). To keep the nomenclature consistent, I renamed the log field.
Once this is merged and Amboy is bumped in Evergreen/Cedar, I'll fix the Splunk Amboy dashboards that currently use "pending_secs" to populate the charts.

EVG-15956: clarify logged timing statistics when job completes

---

queue/group_local.go
queue/group_remote_mongo.go
queue/group_remote_mongo_single.go
queue/group_remote_mongo_test.go
queue/group_test.go
queue/util_for_test.go

Jira: https://jira.mongodb.org/browse/EVG-16210
When the queue group is first started, it initializes queues that already exist and are active (i.e. have incomplete jobs) in the cache based on the DB state. However, the cached queues don't have the ability to set their queue options after the queue is already in the cache since it's considered active and running. This provides a feature to allow users to specify the initial options for individual queues during queue group initialization to ensure that they get the desired options.
* Add per-queue options that can be set during queue group initialization.
* Rename the default queue options to avoid ambiguity.

EVG-16210: add per-queue initialization options for the queue group

---

queue/driver_mongo.go
queue/remote_unordered_test.go

Jira: https://jira.mongodb.org/browse/EVG-16648
I removed the unfulfilled TODO and another outdated TODO. Unfortunately, we can't get rid of the hand-fashioned logic to find/parse the duplicate key errors from MongoDB because [the function referenced in the TODO](https://github.com/mongodb/mongo-go-driver/blob/213fb80b373f70dba4f9f516dc4c718abe41c76b/mongo/errors.go#L87-L96) only tells you if there is a duplicate key error, not which keys are duplicated. Therefore, we still have to parse the error message string to know which individual keys were duplicated.

EVG-16648: remove duplicate key check TODO

---

queue/driver_mongo.go
queue/queue_test.go

https://jira.mongodb.org/browse/EVG-15581
Dispatch by was changed to an `omitempty` field sometime late in 2021. It should be fine to remove the zero time check since the 90 day job TTL has elapsed on all the app servers.
* Remove unnecessary zero time check for dispatch by.
* Small fix for a bug in the way the dispatch by/wait until tests are written.

EVG-15581: remove extra zero-value dispatch by check

---

pool/helpers.go

Jira: https://jira.mongodb.org/browse/EVG-16819
Include the queue ID when logging at the end of a job, which includes useful metadata such as the queue group name (if it's a queue group).

EVG-16819: log queue ID when job finishes

---

registry/interchange.go

Jira: https://jira.mongodb.org/browse/EVG-15582
We can remove the deprecated enqueue scopes field. It's been replaced by two fields (`EnqueueScopes` and `EnqueueAllScopes`), and the 90 day TTL has elapsed, so no jobs have this deprecated field anymore.

EVG-15582: remove deprecated enqueue scopes field

---

queue/group_remote_mongo.go
queue/group_remote_mongo_test.go

Jira: https://jira.mongodb.org/browse/EVG-17370
We already have options that can be applied to specific named queues in the queue group. This adds the ability to apply queue settings to named queues that match a regexp instead of an exact matching name.

EVG-17370: support named queue settings matching a regexp

---

README.rst

Jira: https://jira.mongodb.org/browse/EVG-17917
Some non-Evergreen developers have expressed interest in using Amboy. This is fine, but it's worth having a warning that it's not a stable library, so it has no promises of backward compatibility.

EVG-17917: document backward compatibility warning

---

queue/group_remote_mongo_single.go
queue/group_remote_mongo_test.go
queue/group_test.go
queue/retry.go

Jira:
https://jira.mongodb.org/browse/EVG-17256
https://jira.mongodb.org/browse/EVG-17378
* When a retryable MongoDB-backed queue still has jobs retrying, ensure that it is still considered active so that it doesn't get pruned from the queue group cache.
* Slightly improve the logging in the retry handler. As far as I can tell, the retry handler did the correct thing in EVG-17256, but it just wasn't clear from the logs.

EVG-17256, EVG-17378: keep queues with retrying jobs active and improve retry handler logging

---

queue/driver_mongo.go

The tests are going to fail, but this should force it to use the expected index at least temporarily.

Add hint for hotfix

---

queue/driver_mongo.go

[EVG-18124](https://jira.mongodb.org/browse/EVG-18124)
We think the hotfix from last night caused amboy to not be able to dispatch non-group jobs since that collection doesn't have this index.
This will only do the hotfix in the case of a group queue.

EVG-18124 check UseGroups

---

queue/driver_mongo.go
queue/driver_test.go

Jira: https://jira.mongodb.org/browse/EVG-13408
* Add more unit tests for basic correctness of the `Next` method, which is used to dispatch jobs to workers.
* Add a doc comment for helpfulness.

EVG-13408: add tests for next job

---

queue/driver_mongo.go
queue/driver_test.go
queue/util.go

Jira: https://jira.mongodb.org/browse/EVG-18129
Make the index pattern hint for the next job query configurable by the user when setting up the MongoDB driver. We could use this in the future as well if we want to explicitly set indexes for other queries. By default, it doesn't hint any index for the query, so applications can pick their desired index according to their needs.

EVG-18129: add option to explicitly specify next job hint

---

interface.go
queue/dispatcher.go
queue/driver_mongo.go
queue/driver_test.go
queue/remote_ordered.go
queue/util.go

Jira: https://jira.mongodb.org/browse/EVG-18128
`CheckWaitUntil` will omit jobs that haven't yet reached their `WaitUntil` requirement from the next job iterator results. However, if `CheckWaitUntil` is disabled, jobs that haven't hit their `WaitUntil` time will appear in the iterator results, so the queue should fall back to checking if `WaitUntil` is satisfied in-memory.

EVG-18128: check wait until in-memory

---

queue/limited.go
queue/limited_test.go
queue/queue_test.go

Jira: https://jira.mongodb.org/browse/EVG-18304
The local limited size queue will currently return an error if you try to enqueue jobs before the workers have started processing the queue. This isn't really necessary (and deviates from how all the other implementations behave), and it should be possible to pre-populate the queue before starting work on it, so I removed this limitation. This feature is useful for testing.

EVG-18304: allow the local limited size queue to accept jobs before processing starts

---

queue/driver_mongo.go
queue/driver_mongo_test.go

[EVG-18240](https://jira.mongodb.org/browse/EVG-18240)
Break the query in two: the stale in-progress part first and, if anything's left of the sample size, the pending part.
It seemed the non-sample case could also be an aggregation so this combines them. It skips the check for exclusivity of sample size and priority since it's an invalid configuration anyways (did I get that right?).

EVG-18240 break up Next query

---

errors.go
interface.go
pool/mock_queue_test.go
queue/driver.go
queue/driver_mongo.go
queue/driver_mongo_test.go
queue/limited.go
queue/limited_serializable.go
queue/remote_base.go

[EVG-20527](https://jira.mongodb.org/browse/EVG-20527)
We observed that inserting many jobs (such as what the populators in evergreen do) takes a while because of all the round trips to the db. PutMany will allow adding many jobs to a queue at once.
It was difficult to decide what to return if there is a mixture of write errors, some duplicate key errors and some not. It seemed like the right thing to do (and the expedient thing for `EnqueueManyUniqueJobs`) was to only return a duplicate job error if the errors were _exclusively_ duplicate key errors. Reading [the driver code](https://github.com/mongodb/mongo-go-driver/blob/7355997933f8522a8a17379918b5cb91ff3674cc/mongo/collection.go#L321-L331) made me relatively confident that at least the driver assumes only one error is ever returned …

EVG-20527 PutMany jobs

---

queue/driver_mongo.go
queue/driver_mongo_test.go

[DEVPROD-69](https://jira.mongodb.org/browse/DEVPROD-69)
If the job slice is empty or nil we should skip doing an insert because the driver returns an error for an empty insert. Not returning an error is consistent with the other remote drivers and queues.

DEVPROD-69 skip insertion of an empty jobs slice

---

evergreen.yaml

[DEVPROD-1717](https://jira.mongodb.org/browse/DEVPROD-1717)
Upgrade mongodb to 7.0. Upgrade mongosh while we're at it.
The expansions weren't being used for the lint variant so for that one instead of being updated they got removed.

DEVPROD-1717 upgrade mongo to 7.0

---

queue/driver_mongo.go

Use the correct logical operator to negate the query. This query fix shouldn't change job dispatching, as this query is indexed and is only used to reduce the number of duplicate job errors due to racing to dispatch jobs that hold the same scopes.
Tested in a local DB to verify that `$nor` performs a logical NOT of the listed clause.

DEVPROD-2303: use correct syntax for findng other jobs holding scopes

---

errors.go

[DEVPROD-7468](https://jira.mongodb.org/browse/DEVPROD-7468)
If the a db write returns errors that aren't duplicate job/scope errors [this call to Cause](https://github.com/mongodb/amboy/blob/4bafe808c506bf69edb54aeddbfa65bb37062fb0/errors.go#L167) gets into an infinite recursion because the returned error implements `Cause`...
Return [a vanilla error](https://github.com/mongodb/grip/blob/584e10f183651989291528fc432824587903b6fd/errors_multi.go#L246) instead.

DEVPROD-7468 don't recursively return a causer

---

interface.go
job/base.go
job/base_test.go
registry/mock_job_for_test.go

[DEVPROD-7311](https://jira.mongodb.org/browse/DEVPROD-7311)
Add helper to check if the job is on its last attempt. This check is done quite a lot in Evergreen already, so I figured we might as well make a helper for it.
Added unit tests.

DEVPROD-7311: add method to check for last job attempt

---

interface.go
queue/dispatcher.go
queue/driver_mongo.go
queue/remote_base.go
registry/interchange.go
registry/interchange_test.go

[DEVPROD-7058](https://jira.mongodb.org/browse/DEVPROD-7058)
The error from the generate.tasks job is that _the job itself_ was too large to save back to the DB when marking it complete, which prevented it from finishing. The only way I could practically see this happening is that the generate.tasks logic produced a huge number of errors that exceeded the MDB doc size limit. The Splunk logs hint that this may be the case, even though they don't directly say it (Splunk has the same issue - it's also unable to log events if the payload is too large).
I opted to truncate the errors when saving them back to the DB. Saving the entire error string back to the job isn't a requirement for Amboy to work correctly, and just knowing that there are errors and having a long snippet of the error is …

DEVPROD-7058: truncate excessive errors when saving job

---

registry/interchange.go

Fix panic truncating errors when there's fewer than `maxNumErrors` of them.

DEVPROD-8844: fix panic truncating errors

---

queue/retry.go
queue/retry_test.go

[DEVPROD-8738](https://jira.mongodb.org/browse/DEVPROD-8738)
Reduce error to warning if job runs out of retries. Keeping this log but reducing the log level makes it so that we can still use it for investigation without triggering the error rate alert. This log is good for investigation purposes because we can't assume that every single job implementation will log something special when it runs out of attempts, and running out of retries could indicate that Evergreen is giving up on doing some work that it ought to do.
As for the question of whether this over-logs and is using up our Splunk log limits, during the insufficient capacity outage, this log only used about 0.05% of our Splunk log limit, so removing it wouldn't make a meaningful difference to our Splunk usage.
I checked the …

DEVPROD-8738: reduce log level for job running out of attempts
